CREATE DATABASE IF NOT EXISTS compta;
USE compta;

CREATE TABLE IF NOT EXISTS ARTICLE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REF VARCHAR(13) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    PRIX DECIMAL(7,2) NOT NULL,
    ID_FOU INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FOURNISSEUR(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOM varchar(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS BON(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUMERO INT,
    DATE_CMDE DATETIME NOT NULL,
    DELAI INT NOT NULL,
    ID_FOU INT NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPO(
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QTE int NOT NULL,
    ID_ART INT NOT NULL,
    ID_BON INT NOT NULL
);

-- Clés primaires
ALTER TABLE ARTICLE ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE BON ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES BON(ID);

