-- INSERTION BON
-- Insertion du bon de commande auprès du fournisseur "Française d'Imports"

-- INSERTION COMPO
-- Insertion de la composition du bon de commande n°001
-- 3 Perceuses P1
-- 4 Meuleuses 125mm
-- 1 Perceuse à colonne

-- INSERTION FOURNISSEUR
INSERT INTO FOURNISSEUR (ID, NOM) VALUES ('Française d’Imports'), ('FDM SA'), ('Dubois & Fils');

-- INSERTION ARTICLES
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('A01', 'Perceuse P1', 74.99, 1);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('F01', 'Boulon laiton 4 x 40 mm (sachet de 10)', 2.25, 2);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('F02', 'Boulon laiton 5 x 40 mm (sachet de 10)', 4.45, 2);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('D01', 'Boulon laiton 5 x 40 mm (sachet de 10)', 4.40, 3);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('A02', 'Meuleuse 125mm', 37.85, 1);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('D03', 'Boulon acier zingué 4 x 40mm (sachet de 10)', 1.80, 3);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('A03', 'Perceuse à colonne', 185.25, 1;
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('D04', 'Coffret mêches à bois', 12.25, 3);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('F03', 'Coffret mêches plates', 6.25, 2);
INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, FOURNISSEUR) VALUES ('F04', 'Fraises d''encastrement', 8.14, 2);

-- INSERTION BON DE COMMANDE
INSERT INTO BON_COMMANDE (NUMERO, FOURNISSEUR) VALUES ('001', 1);

-- INSERTION DONNES BON DE COMMANDE
INSERT INTO COMPO (ID_ART, ID_BON, QTE), VALUES (1, 1, 3), (5, 1, 4), (7, 1, 1)
