-- a. Mettez en minuscules la désignation de l'article dont l'identifiant est 2
-- b. Mettez en majuscules les désignations de tous les articles dont le prix est strictement supérieur à 10€
-- c. Baissez de 10% le prix de tous les articles qui n'ont pas fait l'objet d'une commande.
-- d. Une erreur s'est glissée dans les commandes concernant Française d'imports. Les chiffres en base ne sont pas bons. Il faut doubler les quantités de tous les articles commandés à cette société.
-- e. Mettez au point une requête update qui permette de supprimer les éléments entre parenthèses dans les désignations. Il vous faudra utiliser des fonctions comme substring et position.